export const CONNECTION_CHANGE = "CONNECTION_CHANGE";
export const ACTION_SELECT_INSTANCE = "ACTION_SELECT_INSTANCE";
export const ACTION_CHANGE_TIMESCALE = "ACTION_CHANGE_TIMESCALE";
export const MESSAGE_RECEIVED = "MESSAGE_RECEIVED";
export const UPDATE_LOCAL_STATE = "UPDATE_LOCAL_STATE";